spring.application.name=a2-springboot

# App Configuration
app.storage.type=${STORAGE_TYPE:memory}

# Server Configuration
server.port=${PORT:8080}

# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/a2db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:db/migration

# Logging
logging.level.com.a2=DEBUG